name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GCE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.GCE_SSH_KEY }}

    - name: Run deployment script on GCE
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_HOST }} 'cd hello-express && bash ~/deploy.sh'
